---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis
  namespace: jeanevangelista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-redis
  template:
    metadata:
      labels:
        app: serverless-redis
    spec:
      containers:
      - name: serverless-redis
        image: jeanevangelista/serverless:redis
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.187"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics" # extension 1
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: REDIS_MONITORING_PERIOD
          value: 5 # extension 2
        - name: ZIPFILE_URL # extension 3
          valueFrom:
            configMapKeyRef:
              name: zipfile
              key: ZIPFILE_URL
        - name: FUNCTION_HANDLER
          value: handler # extension 4